<?php
/**
 * The template for displaying all pages
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site may use a
 * different template.
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/
 *
 * @package FVICS_by_Adam_H
 */

get_header();
?>

	<main id="primary" class="site-main">

	<div class="posts-carousel px-5">
   <!--Slide One-->
   <div class="card">
      <img width="350" height="233" src="https://via.placeholder.com/150" class="w-100" alt="alt-text">
      <div class="card-body">
         <h3 class="card-title">Your Post heading0</h3>
         <p>Your Post Excerpt</p>
         <a href="#" class="btn btn-primary">View More</a>
      </div>
   </div>
   <!--Slide Two-->
   <div class="card">
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
      <div class="card-body">
         <h3 class="card-title">Your Post heading1</h3>
         <p>Your Post Excerpt</p>
         <a href="#" class="btn btn-primary">View More</a>
      </div>
   </div>
   <!-- Slide Three -->
   <div class="card">
      <img width="350" height="233" src="https://via.placeholder.com/150" class="w-100" alt="alt-text">
      <div class="card-body">
         <h3 class="card-title">Your Post heading2</h3>
         <p>Your Post Excerpt</p>
         <a href="#" class="btn btn-primary">View More</a>
      </div>
   </div>
   <!-- Slide Four -->
   <div class="card">
      <img width="350" height="233" src="https://via.placeholder.com/150" class="w-100" alt="alt-text">
      <div class="card-body">
         <h3 class="card-title">Your Post heading3</h3>
         <p>Your Post Excerpt</p>
         <a href="#" class="btn btn-primary">View More</a>
      </div>
   </div>
</div>

<!-- 'Welcome' Section Left Side Text -->
<section class="home-page-grid">
   <div>
      <p>Welcome Section, left side.</p>
      <p>Blurb generated by acf text field on 'home/options' page, and image will also be acf image field from same page</p>
      <button>About us</button>
      <button>Our History</button>
   </div>
   <div>
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
   </div>
</section>

<!-- News section - uses two images side by side with a small gap in between.  -->
<section class="home-page-grid">
   <!-- this div uses the most recent news article, with the featured image -->
   <div>
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
   </div>
   <!-- this div is going to show the title and featured image of either the second most recent update, or a specific photo. tbd -->
   <div>
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
   </div>
</section>

<!-- Events Section Left Side Text -->
<section class="home-page-grid">
   <div>
      <p>This is the left side, where the calendar widget is going to go</p>
      <p>The other side will be the featured image from the most recent event. Featured or otherwise</p>
   </div>
   <div>
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
   </div>
</section>

<!-- Events Section right side text -->
<section class="home-page-grid">
   <div>
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
   </div>
   <div>
      <p>right side of the events section</p>
      <p>this one has a "blurb" about galleries and past events</p>
      <p>The image over there is the most recent 'past' event that's been posted as a gallery or recap</p>
      <button>See Event Galleries</button>
   </div>
</section>

<!-- Contact Section Left Side Text -->
<section class="home-page-grid">
   <div>
      <p>This is the left side, where the blur about meet the directors is going to go.</p>
      <p>this text will be generated by acf field on a "home/options" page. 
      <p>The other side will be an acf image field on the 'home/options' page.</p>
      <button>Meet our directors</button>
   </div>
   <div>
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
   </div>
</section>

<!-- Contact Section right side text -->
<section class="home-page-grid">
   <div>
      <img src="http://localhost/fvics/wp-content/uploads/2023/08/canmandawe-ftTsK4QinMw-unsplash-scaled.jpg" alt="alt-text">
   </div>
   <div>
      <p>right side of the contact</p>
      <p>this one has a "blurb" about got a question</p>
      <p>text is acf field on 'home/options' page, and image is acf field on 'home/options' page</p>
      <button>contact us</button>
   </div>
</section>



		<?php
		// while ( have_posts() ) :
			// the_post();

			// get_template_part( 'template-parts/content', 'page' );

		// endwhile; // End of the loop.
		?>

	</main><!-- #main -->

<?php
get_sidebar();
get_footer();
